version: '3.8'

services:

  #php
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydramgames-app
    restart: always
    ports:
      - "5173:5173"
      - "6001:6001"
    working_dir: /var/www
    volumes:
      - ./application:/var/www
      - ./.nginx/certs:/etc/ssl/private

  #webserver
  nginx:
    image: nginx:1.25-alpine
    container_name: mydramgames-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/var/www
      - ./.nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./.nginx/certs:/etc/ssl/private

  #database
  db:
    image: mysql:latest
    container_name: mydramgames-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.data/mysql:/var/lib/mysql

